"""CSV column headers — must match on-boarding/assets/data.js templates."""

TEMPLATE_HEADERS: dict[str, list[str]] = {
    "departments": [
        "building_block",
        "department",
        "department_description",
        "subspecialty",
        "subspecialty_description",
        "floor",
        "ward_list",
    ],
    "units": ["building_block", "unit", "floor"],
    "staff": [
        "email",
        "first_name",
        "last_name",
        "job_title",
        "rank",
        "middle_name",
        "phone",
        "gender",
        "department",
        "subspecialty",
        "patient_access",
        "employee_id",
        "highest_qualifications",
    ],
    "roles": [
        "role_name",
        "role_description",
        "department",
        "subspecialty",
        "priority",
        "restricted_signin",
        "permitted_signin_emails",
        "external_communication",
        "escalation",
    ],
    "patients": [
        "first_name",
        "last_name",
        "middle_name",
        "dob",
        "medical_record_number",
        "gender",
        "department",
        "subspecialty",
        "floor",
        "ward",
        "bed",
    ],
}
